name: CI/CD Kubsh

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt update && sudo apt install -y build-essential g++ pkg-config libfuse3-dev libreadline-dev docker.io

    - name: Build kubsh
      run: make all

    - name: Build .deb package
      run: make deb

    - name: Run tests in Docker
      run: make test

    - name: Upload .deb as artifact
      uses: actions/upload-artifact@v3
      with:
        name: kubsh-deb
        path: kubsh_1.0.0_amd64.deb

